//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri radu sa datotekama.
        /// </summary>
        public static string exceptionFile {
            get {
                return ResourceManager.GetString("exceptionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju protivnika.
        /// </summary>
        public static string exceptionOpp {
            get {
                return ResourceManager.GetString("exceptionOpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška pri učitavanju timova.
        /// </summary>
        public static string exceptionTeams {
            get {
                return ResourceManager.GetString("exceptionTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svjetsko prvenstvo.
        /// </summary>
        public static string mainWindowTitle {
            get {
                return ResourceManager.GetString("mainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string settingsCancel {
            get {
                return ResourceManager.GetString("settingsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite prvenstvo:.
        /// </summary>
        public static string settingsChampionship {
            get {
                return ResourceManager.GetString("settingsChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski jezik.
        /// </summary>
        public static string settingsCro {
            get {
                return ResourceManager.GetString("settingsCro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski jezik.
        /// </summary>
        public static string settingsEn {
            get {
                return ResourceManager.GetString("settingsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko svjetsko prvenstvo.
        /// </summary>
        public static string settingsFemaleChamp {
            get {
                return ResourceManager.GetString("settingsFemaleChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik:.
        /// </summary>
        public static string settingsLanguage {
            get {
                return ResourceManager.GetString("settingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško svjetsko prvenstvo.
        /// </summary>
        public static string settingsMaleChamp {
            get {
                return ResourceManager.GetString("settingsMaleChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite rezoluciju:.
        /// </summary>
        public static string settingsResolution {
            get {
                return ResourceManager.GetString("settingsResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string settingsSave {
            get {
                return ResourceManager.GetString("settingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o ekipi.
        /// </summary>
        public static string teamInfo {
            get {
                return ResourceManager.GetString("teamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa kod.
        /// </summary>
        public static string teamInfoCode {
            get {
                return ResourceManager.GetString("teamInfoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeni golovi.
        /// </summary>
        public static string teamInfoConceded {
            get {
                return ResourceManager.GetString("teamInfoConceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neriješeno.
        /// </summary>
        public static string teamInfoDraw {
            get {
                return ResourceManager.GetString("teamInfoDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gol razlika.
        /// </summary>
        public static string teamInfoGADiff {
            get {
                return ResourceManager.GetString("teamInfoGADiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porazi.
        /// </summary>
        public static string teamInfoLoss {
            get {
                return ResourceManager.GetString("teamInfoLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string teamInfoName {
            get {
                return ResourceManager.GetString("teamInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrane utakmice.
        /// </summary>
        public static string teamInfoPlayed {
            get {
                return ResourceManager.GetString("teamInfoPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeni golovi.
        /// </summary>
        public static string teamInfoScored {
            get {
                return ResourceManager.GetString("teamInfoScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede.
        /// </summary>
        public static string teamInfoWins {
            get {
                return ResourceManager.GetString("teamInfoWins", resourceCulture);
            }
        }
    }
}
